export const PERSONAL_THEMES = {
  default: {
    label: 'Moonlit (Default)',
    fontHeading: 'inherit',
    fontBody: 'inherit',
    fixed: false, // follows real moon phase colors
  },
 midnight: {
  label: 'Midnight',
  background: '#05060f',
  accent: '#8b8fa3',
  accentSoft: '#2a2d3d',
  text: '#c9d6ff',
  surface: 'rgba(255,255,255,0.05)',
  fontHeading: 'inherit',
  fontBody: 'inherit',
  fixed: true,
},
  lavenderSky: {
    label: 'Lavender Sky',
    background: '#1a1533',
    accent: '#c9a9ff',
    text: '#c9d6ff',
    surface: 'rgba(255,255,255,0.05)',
    fontHeading: 'inherit',
    fontBody: 'inherit',
    fixed: true,
  },
  forestNight: {
    label: 'Forest Night',
    background: '#0d1f1a',
    accent: '#8fd9b6',
    text: '#c9d6ff',
    surface: 'rgba(255,255,255,0.05)',
    fontHeading: 'inherit',
    fontBody: 'inherit',
    fixed: true,
  },
  autumnGlow: {
    label: 'Autumn Glow',
    background: '#2b1810',
    accent: '#f2a65a',
    text: '#c9d6ff',
    surface: 'rgba(255,255,255,0.05)',
    fontHeading: 'inherit',
    fontBody: 'inherit',
    fixed: true,
  },
  whimsical: {
    label: '☁️ Whimsical Dreams',
    background: 'linear-gradient(160deg, #b8c6f0 0%, #c9b8f0 50%, #e0c9f0 100%)',
    surface: 'rgba(255, 255, 255, 0.55)',
    accent: '#6d5bd0',
    accentSoft: '#e8def8',
    text: '#3d3560',
    fontHeading: "'Quicksand', sans-serif",
    fontBody: "'Quicksand', sans-serif",
    fixed: true,
  },
}